# Generated by Django 4.0.6 on 2022-07-11 04:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('composition_ID', models.AutoField(primary_key=True, serialize=False)),
                ('composer_Name', models.CharField(max_length=20)),
                ('composition_Name', models.CharField(max_length=20)),
                ('date_Last_Performed', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(default=datetime.time(4, 30, 30, 53613))),
                ('compositions', models.ManyToManyField(to='app.composition')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2022, 7, 11))),
            ],
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('conductor_ID', models.AutoField(primary_key=True, serialize=False)),
                ('conductor_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('movement_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('movement_Number', models.IntegerField()),
                ('movement_Name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Soloist',
            fields=[
                ('soloist_ID', models.AutoField(primary_key=True, serialize=False)),
                ('soloist_Name', models.CharField(max_length=20)),
                ('compositions', models.ManyToManyField(blank=True, default=None, to='app.composition')),
            ],
        ),
        migrations.CreateModel(
            name='ConcertSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_date', models.DateField(default=datetime.date(2022, 7, 11))),
                ('concerts', models.ManyToManyField(to='app.concert')),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='concert_Date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.concertdate'),
        ),
        migrations.AddField(
            model_name='concert',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.conductor'),
        ),
        migrations.AddField(
            model_name='composition',
            name='movement_ID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.movement'),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.concert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
